seed_everything: 1555
trainer:
    precision: 32
    max_epochs: 100
    # fast_dev_run: True
    accelerator: 'cuda'
    devices: [0,1]
    logger:
        class_path: aim.pytorch_lightning.AimLogger
        init_args:
            experiment: 'autoint_stpp'
            repo: .blackhole
    log_every_n_steps: 1
    callbacks:
        - class_path: ModelCheckpoint
          init_args:
            monitor: val_nll
model:
    class_path: models.lightning.autoint_stpp.AutoIntSTPointProcess
    init_args:
        n_prodnet: 10
        hidden_size: 128
        num_layers: 2
        activation: tanh
        learning_rate: 0.004
        step_size: 20
        gamma: 0.5
        nsteps: [101, 101, 101]
        round_time: true
        trunc: true
        vis_type: ['interactive', 'static']
        start_idx: [0, 2]
        name: ETAS_incomplete_25
data:
    class_path: data.lightning.sliding_window.SlidingWindowDataModule
    init_args:
        batch_size: 128
        num_workers: 8
        name: ETAS_incomplete_25
        option: ready
catalog:
    Mcut: 2.5
    path: ../../Datasets/ETAS/ETAS_California_incomplete_catalog.csv
    path_to_polygon: ../../Datasets/ETAS/california_shape.npy
    auxiliary_start: 1971-01-01 00:00:00
    train_nll_start: 1981-01-01 00:00:00
    val_nll_start: 1998-01-01 00:00:00
    test_nll_start: 2007-01-01 00:00:00
    test_nll_end: 2020-01-17 00:00:00
